# Task 1: Identity Card(by input funtion)
name=input("Enter your Name: ")
age=input("Enter your Age: ")
city=input("Enter City Name: ")
dob=input("Enter your Date of Birth: ")
collage=input("Enter Collage Name: ")
blood_group=input("Enter your Blood Group: ")
mobile_no=input("Enter Mobile Number: ")
roll_no=input("Enter your Roll No.: ")

print()
print("TASK 1: Identity Card")
print()
print("----- My ID Card -----")
print("Name:",name)
print("Age:",age)
print("City:",city)
print("DOB:",dob)
print("Collage:",collage)
print("Blood Group:",blood_group)
print("Mobile No:",mobile_no)
print("Roll No:",roll_no)
print("-----------------------")
print()


# Task 2: Memory Dectective(by input funtion)
v1=input("Enter value of v1: ")
v2=input("Enter value of v2: ")
v3=input("Enter value of v3: ")

print("TASK 3: Memory Dectective")
print()
print("Memory address of v1 (",v1,"):",id(v1))
print("Memory address of v2 (",v2,"):",id(v2))
print("Memory address of v3 (",v3,"):",id(v3))
print()
print("Conclusion: When you use the input() function in Python, variables end up with different memory addresses even though they contain the exact same string value.")
print()